---
name: "Simple Checks"

on:
  workflow_call:

jobs:
  lint-yaml:
    name: Lint Yaml Files
    runs-on: containers-runner
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: shell
          filters: |
            yaml:
              - added|modified: "**.yaml"
              - added|modified: "**.yml"

      - name: "Yamllint"
        if: ${{ steps.filter.outputs.yaml == 'true' }}
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_file_or_dir: "${{ steps.filter.outputs.yaml_files }}"
          yamllint_strict: false
          yamllint_comment: true
          yamllint_config_filepath: .github/lint/yamllint.yaml
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  metadata-validation:
    name: Validate Image Metadata
    runs-on: containers-runner
    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: shell
          filters: |
            cue:
              - added|modified: "apps/**/metadata.yaml"
              - added|modified: "./.github/lint/metadata.rules.cue"

      - name: Setup CUE
        if: ${{ steps.filter.outputs.cue == 'true' }}
        uses: cue-lang/setup-cue@1713281ae501e533ff06108005dffeab9e2e5203

      - name: Validate image metadata
        if: ${{ steps.filter.outputs.cue == 'true' }}
        shell: bash
        # Run against all files to ensure they are tested if the cue schema is changed.
        run: |
          find ./apps/ -name metadata.json | xargs -I {} cue vet --schema '#Spec' {} ./.github/lint/metadata.rules.cue
          find ./apps/ -name metadata.yaml | xargs -I {} cue vet --schema '#Spec' {} ./.github/lint/metadata.rules.cue
